package mapRunner.customer;

public class CustomerView extends javax.swing.JFrame {

	private static final long serialVersionUID = 7764945658121492598L;

    public CustomerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfAgent = new javax.swing.JTextField();
        lAgent = new javax.swing.JLabel();
        lTarget = new javax.swing.JLabel();
        tfTarget = new javax.swing.JTextField();
        bRun = new javax.swing.JButton();
        lStatus = new javax.swing.JLabel();
        bRunA = new javax.swing.JButton();
        bRunRight = new javax.swing.JButton();
        bRunLeft = new javax.swing.JButton();
        bRunForward = new javax.swing.JButton();
        bRunB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tfAgent.setText("runner");

        lAgent.setText("Agent");

        lTarget.setText("Target");

        tfTarget.setText("1");

        bRun.setText("run");
        bRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRunActionPerformed(evt);
            }
        });

        lStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lStatus.setText("status");

        bRunA.setText("A");
        bRunA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRunAActionPerformed(evt);
            }
        });

        bRunRight.setText("right");
        bRunRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRunRightActionPerformed(evt);
            }
        });

        bRunLeft.setText("left");
        bRunLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRunLeftActionPerformed(evt);
            }
        });

        bRunForward.setText("forward");
        bRunForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRunForwardActionPerformed(evt);
            }
        });

        bRunB.setText("B");
        bRunB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRunBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lAgent)
                            .addComponent(lTarget))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTarget)
                            .addComponent(tfAgent, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))
                    .addComponent(lStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRunLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bRunB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRunA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bRunForward, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(bRunRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAgent)
                    .addComponent(bRunLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRun, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTarget)
                    .addComponent(tfTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRunRight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRunA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStatus)
                    .addComponent(bRunForward, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRunB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRunActionPerformed
    	agent.sendTargetToRunner(tfAgent.getText(), tfTarget.getText());        
    }//GEN-LAST:event_bRunActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        agent.doDelete();
    }//GEN-LAST:event_formWindowClosing

    private void bRunRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRunRightActionPerformed
        agent.sendTargetToRunner(tfAgent.getText(), "r");
    }//GEN-LAST:event_bRunRightActionPerformed

    private void bRunAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRunAActionPerformed
        agent.sendTargetToRunner(tfAgent.getText(), "A");
    }//GEN-LAST:event_bRunAActionPerformed

    private void bRunBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRunBActionPerformed
        agent.sendTargetToRunner(tfAgent.getText(), "B");
    }//GEN-LAST:event_bRunBActionPerformed

    private void bRunLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRunLeftActionPerformed
        agent.sendTargetToRunner(tfAgent.getText(), "l");
    }//GEN-LAST:event_bRunLeftActionPerformed

    private void bRunForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRunForwardActionPerformed
        agent.sendTargetToRunner(tfAgent.getText(), "f");
    }//GEN-LAST:event_bRunForwardActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRun;
    private javax.swing.JButton bRunA;
    private javax.swing.JButton bRunB;
    private javax.swing.JButton bRunForward;
    private javax.swing.JButton bRunLeft;
    private javax.swing.JButton bRunRight;
    private javax.swing.JLabel lAgent;
    private javax.swing.JLabel lStatus;
    private javax.swing.JLabel lTarget;
    private javax.swing.JTextField tfAgent;
    private javax.swing.JTextField tfTarget;
    // End of variables declaration//GEN-END:variables
    
    CustomerAgent agent;
    
    public void showStatus(String status) {
    	lStatus.setText(status);
    }
}
